### ISSUE TITLE
Sideloadable ipa

### ISSUE THREAD

**Issue by bingoxo** [haoict/iconcert#4]
Can you please make a Sideloadable ipa For non jailbroken devices ?

**Comment by haoict** [comment]
what??? this is not a tweak for app

**Comment by bingoxo** [comment]
I know but can it be made as standalone app for non jailbroken ?

**Comment by haoict** [comment]
idk what you mean

**Comment by bingoxo** [comment]
How can icon cert work for non jailbroken devices (who sideload apps) ?

**Comment by haoict** [comment]
This hooks into Springboard, which is not an app so it can't be sideloadable :)
